apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-gh-action
  labels:
    app: test-gh-action
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-gh-action
  template:
    metadata:
      labels:
        app: test-gh-action
    spec:
      containers:
      - name: test-gh-action
        image: triquenguyen/pi-test:0.0.7
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"