name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"] # This workflow runs after the build workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: [self-hosted, linux/arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy App (Deployment)
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f .github/deploy/deployment.yaml
      
      - name: Deploy App (Service)
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f .github/deploy/service.yaml