name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        platform: linux/arm64
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: triquenguyen/pi-test:latest

      # - name: Build and push Docker image
      #   run: |
      #     docker buildx build --platform linux/arm64 -t triquenguyen/pi-test:latest --push .

